"
This class represents an overload Card
"
Class {
	#name : 'OverloadCard',
	#superclass : 'Card',
	#category : 'IngSoft2-Model',
	#package : 'IngSoft2-Model'
}

{ #category : 'as yet unclassified' }
OverloadCard >> applyEffectPlayedBy: aPlayingShip affecting: anAffectedCard and: anAffectedShip in: aGame [

	aGame validateNextPlayer: aPlayingShip.
	anAffectedShip applyRollModifier: -2.
	aGame lastPlayedCard: self.
	aGame addActiveCard: self
]

{ #category : 'playing' }
OverloadCard >> bePlayedBy: aPlayingShip affecting: anAffectedCard and: anAffectedShip in: aGame [

	self
		applyEffectPlayedBy: aPlayingShip
		affecting: anAffectedCard
		and: anAffectedShip
		in: aGame.
	aPlayingShip remove: self
]

{ #category : 'cancelling' }
OverloadCard >> cancelEffectIn: aGame [

	aGame applyRollModifier: 2
]

{ #category : 'comparing' }
OverloadCard >> compare: aShip and: anotherShip [

	^ false
]
